
  // DON'T edit the quiz data here.
  // The data is taken from this spreadsheet: https://docs.google.com/spreadsheets/d/1VWTFG-FPVwcEZcZYXRznONFE3gOIS99LrXajChCl33E/edit?usp=sharing
  // This file is generated with a Python script from the sheet.
  
const quiz_data = {
  "intro": {
    "eng": [
      [
        "Scratch is...",
        "a programming language",
        "an educational videogame",
        "a video communication software",
      ],
      [
        "To get started with Scratch, you need...",
        "a laptop and a mouse",
        "pen and paper",
        "a smartphone",
      ],
      [
        "With Scratch you CAN'T create...",
        "a mobile app",
        "a videogame",
        "an animation",
      ],
      [
        "Scratch is available in...",
        "more than 70 languages",
        "European languages only",
        "English only",
      ],
      [
        "Until you confirm your Scratch account, you CAN'T...",
        "share your projects",
        "draw new costumes",
        "use Scratch at all",
      ],
      [
        "Scratch blocks give tasks to...",
        "a sprite",
        "a subroutine",
        "an AI chatbot",
      ],
      [
        "When someone shares a project, you CAN'T...",
        "change the original project",
        "play it until they give permission",
        "remix it to create your own version",
      ],
      [
        "Reactions to a project include...",
        "loving, favoriting, and commenting",
        "rating with 1 to 5 stars",
        "liking, disliking, and sharing",
      ],
      [
        "You can find someone's account by...",
        "searching their usernames",
        "sending them a private message",
        "giving them your password",
      ],
    ],
    "hun": [
      [
        "A Scratch...",
        "egy programozási nyelv",
        "egy oktatási célú videojáték",
        "egy videokommunikációs szoftver",
      ],
      [
        "A Scratchezéshez szükséged lesz...",
        "laptopra és egérre",
        "tollra és papírra",
        "okostelefonra",
      ],
      [
        "A Scratch NEM alkalmas...",
        "mobilapp fejlesztésére",
        "videojáték fejlesztésére",
        "animáció készítésére",
      ],
      [
        "A Scratch elérhető...",
        "több mint 70 nyelven",
        "a fontosabb európai nyelveken",
        "egyelőre csak angolul",
      ],
      [
        "A Scratch fiókod visszaigazolásáig nem tudod...",
        "megosztani a projektjeidet",
        "magad rajzolni a szereplőidet",
        "a Scratchet használni",
      ],
      [
        "A Scratch blokkok feladatokat adnak...",
        "egy szereplőnek",
        "egy szubrutinnak",
        "egy AI chatbotnak",
      ],
      [
        "Ha valaki megosztott egy projektet, NEM tudod...",
        "az eredetit módosítani",
        "lejátszani addig, amíg nem ad rá engedélyt",
        "remixelve létrehozni a saját verziódat",
      ],
      [
        "A más projektjére reagálhatsz...",
        "szívecskével, csillaggal és kommenttel",
        "1-5 csillagos értékeléssel",
        "like, dislike és megosztás gombokkal",
      ],
      [
        "A berátod fiókját megtalálod...",
        "ha rákeresel a felhasználónevére",
        "ha küldesz neki privát üzenetet",
        "ha megosztod vele a jelszavadat",
      ],
    ],
    "ukr": [
      [
        "Скретч - це...",
        "мова програмування",
        "навчальна відеогра",
        "програма для відеозв'язку",
      ],
      [
        "Щоб почати працювати зі Scratch, тобі потрібно...",
        "ноутбук і миша",
        "ручка та папір",
        "смартфон",
      ],
      [
        "За допомогою Scratch не можна створити...",
        "мобільний додаток",
        "відеогру",
        "анімацію",
      ],
      [
        "Скретч доступний...",
        "більш ніж 70 мовами",
        "лише європейські мови",
        "лише англійською",
      ],
      [
        "Поки ти не підтвердиш свій обліковий запис Scratch, ти не зможеш...",
        "ділитися своїми проектами",
        "малювати нові костюми",
        "використовувати Скретч взагалі",
      ],
      [
        "Скретч-блоки дають завдання...",
        "спрайту",
        "підпрограмі",
        "чат-боту зі штучним інтелектом",
      ],
      [
        "Коли хтось ділиться проєктом, ви НЕ МОЖЕТЕ...",
        "змінювати оригінальний проєкт",
        "відтворювати його, поки він не дасть дозволу",
        "реміксувати його, щоб створити власну версію",
      ],
      [
        "Реакції на проект включають...",
        "вподобання, вподобання та коментарі",
        "оцінка від 1 до 5 зірок",
        "вподобання, не вподобання та поширення",
      ],
      [
        "Ви можете знайти чийсь обліковий запис за допомогою...",
        "пошуку за іменами користувачів",
        "надіславши йому приватне повідомлення",
        "повідомивши йому свій пароль",
      ],
    ],
  },
  "drawing": {
    "eng": [
      [
        "With Scratch you can create and edit... ",
        "vector and bitmap images",
        "2d, 3d, and 4d images ",
        "AI generated photos",
      ],
      [
        "A vector image consists of...",
        "objects with shape and color data",
        "pixels with color and transparency data",
        "sprites with various costumes",
      ],
      [
        "You can open the graphic editor clicking on...",
        "the Costumes tab",
        "the Code tab",
        "the Sounds tab",
      ],
      [
        "You can create complex shapes from simple ones with...",
        "the Reshape tool",
        "the Brush tool",
        "the Select tool",
      ],
      [
        "To create many instances of a shape, use...",
        "Ctrl C, Ctrl V",
        "the Fill tool",
        "the Flip tool",
      ],
      [
        "A selected shape can be rotated with...",
        "the curved arrow below the selection",
        "the Rotate tool",
        "the right button of your mouse",
      ],
      [
        "A gradient can be...",
        "horizontal, vertical, or radial",
        "left-handed or right-handed",
        "positive or negative",
      ],
      [
        "Scratch blends a color from three components:",
        "color, saturation, brightness",
        "red, green, blue",
        "horizontal, vertical, radial",
      ],
    ],
    "hun": [
      [
        "A Scratch alkalmas...",
        "vektoros képek és bitképek szerkesztésére",
        "2d, 3d és 4d képek szerkesztésére",
        "AI fotók generálására",
      ],
      [
        "Egy vektoros kép összetevői",
        "objektumok az alakjukat és a színüket leíró adatokkal",
        "pixelek szín- és átlátszósági adatokkal",
        "szereplők különféle jelmezekkel",
      ],
      [
        "A grafikus szerkesztőt megnyithatod...",
        "a Jelmezek fülre kattintva",
        "a Kód fülre kattintva",
        "a Hangok fülre kattintva",
      ],
      [
        "Egyszerű formát komplexszé alakíthatsz... ",
        "az Újraformálás eszközzel",
        "a Kör eszközzel",
        "a Kijelölés eszközzel",
      ],
      [
        "Ha egy alakzatot meg akarsz sokszorozni, használd...",
        "a Ctrl C-t és a Ctrl V-t",
        "a Kitöltés eszközt",
        "a Tükrözés eszközt",
      ],
      [
        "Egy kiválasztott alakzatot elforgathatsz...",
        "a kijelölés alatti ívelt nyíllal",
        "az Elforgatás eszközzel",
        "a jobb egérgomboddal",
      ],
      [
        "Egy színátmenet lehet...",
        "vízszintes, függőleges vagy középpontos",
        "balkezes vagy jobbkezes",
        "pozitív vagy negatív",
      ],
      [
        "A Scratch három komponensből keveri a színeket:",
        "szín, telítettség, fényerő",
        "vörös, zöld, kék",
        "vízszintes, függőleges, középpontos",
      ],
    ],
    "ukr": [
      [
        "За допомогою Scratch ви можете створювати та редагувати",
        "векторні та растрові зображення",
        "2d, 3d та 4d зображення ",
        "фотографії, згенеровані штучним інтелектом",
      ],
      [
        "Векторне зображення складається з...",
        "об'єктів з даними форми та кольору",
        "пікселів з даними про колір і прозорість",
        "спрайтів з різними костюмами",
      ],
      [
        "Ви можете відкрити графічний редактор, натиснувши на...",
        "вкладку Образи",
        "вкладку Код",
        "вкладку Звуки",
      ],
      [
        "Ви можете створювати складні фігури з простих за допомогою...",
        "інструментом Реформувати",
        "інструментом Пензель",
        "інструмент Обрати",
      ],
      [
        "Щоб створити багато екземплярів фігури, використовуйте...",
        "Ctrl C, Ctrl V",
        "інструмент заповнення",
        "інструмент право-ліво",
      ],
      [
        "Виділену фігуру можна обертати за допомогою...",
        "вигнутою стрілкою під виділеною фігурою",
        "інструмент Обертання",
        "правою кнопкою миші",
      ],
      [
        "Градієнт може бути...",
        "горизонтальним, вертикальним або радіальним",
        "лівостороннім або правостороннім",
        "позитивним або негативним",
      ],
      [
        "Скретч змішує колір з трьох компонентів:",
        "колір, насиченість, яскравість",
        "червоний, зелений, синій",
        "горизонтальний, вертикальний, радіальний",
      ],
    ],
  },
  "motion": {
    "eng": [
      [
        "Motion blocks are...",
        "blue",
        "green",
        "yellow",
      ],
      [
        "x and y coordinates specify a sprite's...",
        "horizontal and vertical position",
        "direction and size",
        "position and velocity",
      ],
      [
        "Moving a sprite up means...",
        "increasing its y coordinate ",
        "decreasing its y coordinate",
        "decreasing its x coordinate",
      ],
      [
        "x and y coordinates tell the position of...",
        "the center of a sprite",
        "the bottom left corner of a sprite",
        "the top left corner of a sprite",
      ],
      [
        "The coordinates of the top left corner of the stage are...",
        "x: -240, y: 180",
        "x: 0, y: 0",
        "x: 240, y: -180",
      ],
      [
        "A \"set x to 100\" block over a \"change x by 100\" results in...",
        "x = 200",
        "x = 0",
        "x = 100",
      ],
      [
        "The difference between \"go to\" and \"glide\" blocks is...",
        "go to is instant; \"glide\" takes time",
        "go to moves sprites; \"glide\" moves the background",
        "go to is a variable, \"glide\" is a list",
      ],
      [
        "The direction of a sprite is a number between",
        "-179 and 180",
        "1 and 100",
        "0 and 1",
      ],
    ],
    "hun": [
      [
        "A mozgás-blokkok...",
        "kékek",
        "sárgák",
        "zöldek",
      ],
      [
        "Az x és y koordináták megadják a szereplő...",
        "vízszintes és függőleges helyzetét",
        "irányát és méretét",
        "helyzetét és sebességét",
      ],
      [
        "Ha felfele mozdul egy szereplő...",
        "nő az y koordinátája",
        "csökken az y koordinátája",
        "csökken az x koordinátája",
      ],
      [
        "Az x és y koordináták egy szereplő...",
        "középpontjának helyzetét",
        "bal alsó sarkának helyzetét",
        "bal felső sarkának helyzetét",
      ],
      [
        "A színpad bal felső sarkának koordinátái:",
        "x: -240, y: 180",
        "x: 0, y: 0",
        "x: 240, y: -180",
      ],
      [
        "x legyen 100 blokk az \"x változzon 100-zal\" blokk felett. Az eredmény:",
        "x = 200",
        "x = 0",
        "x = 100",
      ],
      [
        "Az \"ugorj\" és a \"csússz\" blokkok közötti különbség:",
        "az \"ugorj\" egy pillanat alatt, a \"csússz\" megadott idő alatt mozgat ",
        "az \"ugorj\" szereplőt mozgat, a \"csússz\" a hátteret",
        "az \"ugorj\" változó, a \"csússz\" lista",
      ],
      [
        "A szereplő iránya egy szám...",
        "-179 és 180 között",
        "1 és 100 között",
        "0 és 1 között",
      ],
    ],
    "ukr": [
      [
        "Блоки руху - це...",
        "синій",
        "зелений",
        "жовтий",
      ],
      [
        "Координати x та y визначають...",
        "горизонтальне та вертикальне положення",
        "напрямок та розмір",
        "положення та швидкість",
      ],
      [
        "Переміщення спрайту вгору означає...",
        "збільшення його координати y",
        "зменшення його координати y",
        "зменшення координати x",
      ],
      [
        "Координати x та y визначають положення...",
        "центру спрайту",
        "нижній лівий кут спрайту",
        "верхнього лівого кута спрайту",
      ],
      [
        "Координати лівого верхнього кута сцени мають вигляд",
        "x: -240, y: 180",
        "x: 0, y: 0",
        "x: 240, y: -180",
      ],
      [
        "Блок \"встановити x рівним 100\" над блоком \"змінити x на 100\" призводить до",
        "x = 200",
        "x = 0",
        "x = 100",
      ],
      [
        "Різниця між блоками \" перемістити\" та \"ковзати\" полягає у тому, що...",
        "перемістити виконується миттєво, а \"ковзати\" - з певним часом",
        "перемістити  переміщує спрайти, а \" ковзати \" переміщує тло",
        "перемістити  - змінна, \" ковзати \" - список",
      ],
      [
        "Напрямок спрайту - це число між ",
        "-179 і 180",
        "1 і 100",
        "0 і 1",
      ],
    ],
  },
  "variables": {
    "eng": [
      [
        "A variable is...",
        "a piece of data with a name",
        "a sprite that changes its size",
        "a project that keeps being rewritten",
      ],
      [
        "Scratch variables can hold...",
        "numbers and texts",
        "scratch blocks",
        "costumes and backgrounds",
      ],
      [
        "To reset the player's score to 0, you need...",
        "the \"set\" block",
        "the \"change\" block",
        "the \"show\" block",
      ],
      [
        "To increment the player's score, you need...",
        "the \"change\" block",
        "the \"repeat until\" block",
        "the \"add\" block",
      ],
      [
        "Which is NOT a valid way to hide a variable from the stage?",
        "Erase it in the graphic editor.",
        "Uncheck the box near its value block.",
        "Add a \"hide variable\" block to your code.",
      ],
      [
        "How many times do you need to repeate the execution of the \"change by (-1)\" block to count down from 30 to 10?",
        "20",
        "-20",
        "10",
      ],
      [
        "The value of score is 10. The result of \"set score to (score / 2)\" is... ",
        "5",
        "20",
        "This doesn't make sense.",
      ],
      [
        "The value of a cloud variable is...",
        "stored on Scratch's s servers",
        "not stored at all",
        "stored on your computer",
      ],
    ],
    "hun": [
      [
        "A változó...",
        "egy adat, aminek nevet adtunk",
        "egy szereplő, amely változtatja a méretét",
        "egy projekt, amit folyton újraírnak",
      ],
      [
        "A Scratch változók értékei lehetnek...",
        "számok vagy szövegek",
        "Scratch blokkok",
        "jelmezek és hátterek",
      ],
      [
        "Hogy lenullázd a játékos pontját, használj...",
        "legyen blokkot",
        "változzon blokkot",
        "mutasd blokkot",
      ],
      [
        "A játékos pontjának növeléséhez használd...",
        "a \"változzon\" blokkot",
        "az \"ismételd eddig\" blokkot",
        "az \"add hozzá\" blokkot",
      ],
      [
        "Hogy NEM lehet eltűntetni egy változót a színpadról?",
        "Kiradírozod a grafikus szerkesztővel",
        "Kikattintod a pipát mellőle,",
        "változó tűnjön el blokkot adsz a kódodhoz.",
      ],
      [
        "Hányszor kell ismételni a \"változzon (-1)\" blokk végrehajtását, hogy 30-tól 10-ig visszaszámláljunk?",
        "20",
        "-20",
        "10",
      ],
      [
        "A pont változó értéke 10. A \"pont legyen (pont / 2)\" eredménye... ",
        "5",
        "20",
        "Ennek nincs értelme.",
      ],
      [
        "Egy felhőváltozó értéke...",
        "a Scratch szerverein tárolódik",
        "sehol nem tárolódik",
        "a te gépeden tárolódik ",
      ],
    ],
    "ukr": [
      [
        "Змінна - це...",
        "дані з іменем",
        "спрайт, який змінює свій розмір",
        "проект, який постійно переписується",
      ],
      [
        "Змінні у Скретч можуть містити...",
        "числа і тексти",
        "скретч-блоки",
        "костюми та фони",
      ],
      [
        "Щоб обнулити рахунок гравця на 0, потрібно...",
        "блок \"set\" ",
        "блок \"змінити\"",
        "блок \"показати\"",
      ],
      [
        "Щоб збільшити рахунок гравця, потрібно...",
        "блок \"змінити\"",
        "блок \"повторювати до\"",
        "блок \"додати\"",
      ],
      [
        "Який спосіб приховати змінну зі сцени НЕ є правильним?",
        "Зітріть її в графічному редакторі. ",
        "Зніміть прапорець біля її блоку значень. ",
        "Додайте до коду блок \"приховати змінну\".",
      ],
      [
        "Скільки разів потрібно повторити виконання блоку \"змінити на (-1)\", щоб почався зворотний відлік від 30 до 10? ",
        "20",
        "-20",
        "10",
      ],
      [
        "Значення рахунку дорівнює 10. Результат виконання блоку \"встановити рахунок на (рахунок / 2)\"...",
        "5",
        "20",
        "Це не має жодного сенсу",
      ],
      [
        "Значення хмарної змінної...",
        "зберігається на серверах Скретч",
        "не зберігається взагалі",
        "зберігається на вашому комп'ютері",
      ],
    ],
  },
}